#!/usr/bin/env python
"""Round 4, PPI track, stage Q1: acceptance of the estimator module.

Two parts, both written into one table (q1_acceptance.csv).

PART 1, B1 CONFIGURATION (source section 6 Q1 acceptance, last item). round4_ppi_estimator
run in B1's configuration (lambda rule 'a_b1', CR1 with t_{G_L - 1}, spot i.i.d. with a normal
reference, percentile donor bootstrap with B1's own seeds and draw order) on B1's sufficient
statistics must reproduce, row by row,
  (a) results/round3/B1_ppi/b1_estimates.csv for every CCRCC row the statistics cover
      (theta, lambda, the three standard errors, the interval ends), and
  (b) results/round3/B1_ppi/b1_acceptance.csv for every CCRCC row of checks 1, 2, 2b, 3, 4
      and 4b, recomputed here by the same statistic B1 used.
The sufficient statistics are the ones regenerated by the Q0 anchor run
(results/round4/ppi/Q0_setup/anchor/run/b1_suffstats__CCRCC__resnet50.npz), which reproduced
B1's committed CCRCC rows with max |diff| 0.0. Tolerance 1e-10.

PART 2, m = 1 (source Q1 acceptance, first item). On synthetic data with one spot per donor,
every clustered variance (CR1 and CR2, both terms, every lambda rule) equals the spot i.i.d.
one to 1e-12.

B1's own functions (load_suff, draw_L, group_mask, NL_SETTINGS) are imported unmodified
from the round-3 script; nothing in round 3 is edited.
"""
import argparse
import json
import os
import sys

import numpy as np
import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import round4_ppi_estimator as E  # noqa: E402


def load_b1():
    import round3_b1_ppi as B  # imported from the same directory (the track's clone)
    return B


def suff_to_donors(d, Lg, Ug):
    """B1's per-slide sufficient statistics (k = 1) to per-donor arrays and donor masks."""
    S1, S2 = d["S1"], d["S2"]
    G = S1.shape[1]
    keep = Lg | Ug
    S = dict(n=np.repeat(d["n_per"][:, None], G, axis=1) * keep[:, None],
             Sz=S1[:, :, 0] * keep[:, None], Sf=S1[:, :, 1] * keep[:, None],
             Szz=S2[:, :, 0, 0] * keep[:, None], Sff=S2[:, :, 1, 1] * keep[:, None],
             Szf=S2[:, :, 0, 1] * keep[:, None])
    nd = int(d["donor_idx"].max()) + 1
    D = E.aggregate_to_donors(S, d["donor_idx"], nd)
    Ld = np.zeros(nd, bool); Ud = np.zeros(nd, bool)
    Ld[np.unique(d["donor_idx"][Lg])] = True
    Ud[np.unique(d["donor_idx"][Ug])] = True
    assert not (Ld & Ud).any(), "regime A: a donor is labelled or it is not"
    return D, np.repeat(Ld[:, None], G, 1), np.repeat(Ud[:, None], G, 1)


def b1_cell(pop, d, Lg, Ug, seed, n_boot, lam_fixed=None, alpha=E.ALPHA):
    """The module in B1's configuration. Returns a dict shaped like B1's cell output."""
    D, Lm, Um = suff_to_donors(d, Lg, Ug)
    G = Lm.shape[1]
    out = {}
    A = Lm | Um
    if pop == "spot":
        out["theta_full"] = E._m(D["Sz"], A) / E._m(D["n"], A)
    else:
        t, _ = E.donor_values(D)
        out["theta_full"] = np.nanmean(np.where(A, t, np.nan), axis=0)
    cnt = {}
    rng = E.seed_rng(seed)
    GL, GU = int(Lm[:, 0].sum()), int(Um[:, 0].sum())
    cnt["L"] = E.draw_counts(GL, n_boot, G, rng, shared=True)
    cnt["U"] = E.draw_counts(GU, n_boot, G, rng, shared=True) if GU else None
    for key, rule in (("cl", "none"), ("pp", "a_b1")):
        if key == "pp" and lam_fixed is not None:
            lam = E.lambda_rule("none", pop, D, Lm, Um)
            lam = dict(lamL=np.full(Lm.shape, float(lam_fixed)), cU=np.full(G, float(lam_fixed)),
                       strata=None, lam=np.full(G, float(lam_fixed)), basis="fixed")
        else:
            lam = E.lambda_rule(rule, pop, D, Lm, Um)
        res = E.estimate(pop, D, Lm, Um, lam)
        v = E.variances(res)
        th = res["theta"]
        out[f"theta_{'classical' if key == 'cl' else 'pp'}"] = th
        if key == "pp":
            out["lambda"] = lam["lam"]
        out[f"se_iid_{key}"] = np.sqrt(np.maximum(v["iid_z"][0], 0.0))
        out[f"se_cluster_{key}"] = np.sqrt(np.maximum(v["CR1_t"][0], 0.0))
        out[f"df_{key}"] = v["CR1_t"][1]
        b = E.bootstrap(pop, D, Lm, Um, lam, th, out[f"se_cluster_{key}"], n_boot=n_boot,
                        alpha=alpha, shared=True, cntL=cnt["L"], cntU=cnt["U"])
        out[f"boot_lo_{key}"], out[f"boot_hi_{key}"] = b["boot_pct"]
        out[f"se_boot_{key}"] = b["se_boot"]
    out["G_L"], out["G_U"] = GL, GU
    return out


def intervals(r, alpha=E.ALPHA):
    from scipy import stats
    z = stats.norm.ppf(1 - alpha / 2)
    o = {}
    for key, nm in (("cl", "classical"), ("pp", "pp")):
        th = r[f"theta_{'classical' if key == 'cl' else 'pp'}"]
        tq = stats.t.ppf(1 - alpha / 2, r[f"df_{key}"])
        o[f"{nm}|iid"] = (th - z * r[f"se_iid_{key}"], th + z * r[f"se_iid_{key}"])
        o[f"{nm}|cluster"] = (th - tq * r[f"se_cluster_{key}"], th + tq * r[f"se_cluster_{key}"])
        o[f"{nm}|boot"] = (r[f"boot_lo_{key}"], r[f"boot_hi_{key}"])
    return o


def part1(suff_dir, b1_dir, n_boot, tol):
    B = load_b1()
    v = "CCRCC"
    est_old = pd.read_csv(f"{b1_dir}/b1_estimates.csv")
    est_old = est_old[est_old.variant == v]
    acc_old = pd.read_csv(f"{b1_dir}/b1_acceptance.csv")
    acc_old = acc_old[acc_old.variant == v]
    rows = []
    # ---- (a) b1_estimates ----
    cols = ["theta_full", "theta_classical", "theta_pp", "lam", "se_iid_classical",
            "se_cluster_classical", "se_boot_classical", "se_iid_pp", "se_cluster_pp",
            "se_boot_pp"] + [f"{nm}_{vr}_{e}" for nm in ("classical", "pp")
                             for vr in ("iid", "cluster", "boot") for e in ("lo", "hi")]
    maxdiff = {c: 0.0 for c in cols}
    n_cmp = 0
    for est in ("theta3", "theta2"):
        for arm in ("resnet50", "permuted"):
            for pop in ("spot", "donor"):
                d = B.load_suff(suff_dir, v, arm, est, pop)
                if d is None:
                    continue
                for n_L in B.NL_SETTINGS[v]:
                    Ld = B.draw_L(d["valid_donors"], n_L, f"{v}|nL{n_L}")
                    Lg = B.group_mask(d, Ld) & d["valid"]
                    Ug = (~B.group_mask(d, Ld)) & d["valid"]
                    r = b1_cell(pop, d, Lg, Ug, f"{v}|{arm}|{est}|{pop}|{n_L}", n_boot)
                    iv = intervals(r)
                    old = est_old[(est_old.arm == arm) & (est_old.estimand == est)
                                  & (est_old.population == pop) & (est_old.n_L_donors == n_L)]
                    old = old.set_index("gene").loc[d["genes"]]
                    new = dict(theta_full=r["theta_full"], theta_classical=r["theta_classical"],
                               theta_pp=r["theta_pp"], lam=r["lambda"])
                    for key, nm in (("cl", "classical"), ("pp", "pp")):
                        for s in ("iid", "cluster", "boot"):
                            new[f"se_{s}_{nm}"] = r[f"se_{s}_{key}"]
                            new[f"{nm}_{s}_lo"], new[f"{nm}_{s}_hi"] = iv[f"{nm}|{s}"]
                    for c in cols:
                        dd = np.abs(np.asarray(new[c], float) - old[c].to_numpy(float))
                        maxdiff[c] = max(maxdiff[c], float(np.nanmax(dd)))
                    n_cmp += len(old)
    worst = max(maxdiff.values())
    rows.append(dict(part="1a_b1_estimates", check="module in B1 configuration reproduces "
                     "b1_estimates.csv (CCRCC)", statistic="max |new - committed| over "
                     f"{len(cols)} columns", value=worst, tol=tol, passed=bool(worst <= tol),
                     detail=f"{n_cmp} rows; worst column "
                            f"{max(maxdiff, key=maxdiff.get)}"))
    # ---- (b) b1_acceptance, the same statistics B1 computes ----
    new_acc = []
    for est in ("theta3", "theta2"):
        for pop in ("spot", "donor"):
            d = B.load_suff(suff_dir, v, B.PERMUTE_SOURCE, est, pop)
            Lg = d["valid"].copy()
            r = b1_cell(pop, d, Lg, ~Lg, f"acc1|{v}|{est}|{pop}", 5)
            new_acc.append(("1_U_empty_pp_equals_classical", est, pop, B.PERMUTE_SOURCE,
                            float(np.max(np.abs(r["theta_pp"] - r["theta_classical"])))))
            di = B.load_suff(suff_dir, v, "identity", est, pop)
            n_L = B.NL_SETTINGS[v][0]
            Ld = B.draw_L(di["valid_donors"], n_L, f"{v}|nL{n_L}")
            Lg = B.group_mask(di, Ld) & di["valid"]
            Ug = (~B.group_mask(di, Ld)) & di["valid"]
            nU, nLs = float(di["n_per"][Ug].sum()), float(di["n_per"][Lg].sum())
            GU = len(set(di["donor_idx"][Ug].tolist()))
            GL = len(set(di["donor_idx"][Lg].tolist()))
            lam_id = (nU / (nU + nLs)) if pop == "spot" else (GU / (GU + GL))
            r = b1_cell(pop, di, Lg, Ug, f"acc2|{v}|{est}|{pop}", 5, lam_fixed=lam_id)
            new_acc.append(("2_perfect_predictions_pp_equals_full", est, pop, "identity",
                            float(np.max(np.abs(r["theta_pp"] - r["theta_full"])))))
            rh = b1_cell(pop, di, Lg, Ug, f"acc2b|{v}|{est}|{pop}", 5)
            new_acc.append(("2b_perfect_predictions_at_estimated_lambda", est, pop, "identity",
                            float(np.max(np.abs(rh["theta_pp"] - rh["theta_full"])))))
            do = B.load_suff(suff_dir, v, B.PERMUTE_SOURCE, est, pop, block="one")
            if do is not None and int(do["valid"].sum()) >= 3:
                n_L = min(max(2, B.NL_SETTINGS[v][0]), int(do["valid"].sum()) - 1)
                Ld = B.draw_L(do["valid_donors"], n_L, f"{v}|one|nL{n_L}")
                Lg = B.group_mask(do, Ld) & do["valid"]
                Ug = (~B.group_mask(do, Ld)) & do["valid"]
                r = b1_cell(pop, do, Lg, Ug, f"acc3|{v}|{est}|{pop}", 5)
                for key, nm in (("cl", "classical"), ("pp", "pp")):
                    a, b = r[f"se_iid_{key}"], r[f"se_cluster_{key}"]
                    ok = np.isfinite(a) & np.isfinite(b) & (a > 0)
                    new_acc.append(("3_one_spot_per_donor_cluster_eq_iid", est, pop,
                                    f"{B.PERMUTE_SOURCE}/{nm}",
                                    float(np.max(np.abs(b[ok] - a[ok]) / a[ok]))))
            dp = B.load_suff(suff_dir, v, "permuted", est, pop)
            for n_L in B.NL_SETTINGS[v]:
                Ld = B.draw_L(dp["valid_donors"], n_L, f"{v}|nL{n_L}")
                Lg = B.group_mask(dp, Ld) & dp["valid"]
                Ug = (~B.group_mask(dp, Ld)) & dp["valid"]
                r = b1_cell(pop, dp, Lg, Ug, f"acc4|{v}|{est}|{pop}|{n_L}", n_boot)
                iv = intervals(r)
                for vr in ("iid", "cluster", "boot"):
                    lo, hi = iv[f"pp|{vr}"]
                    clo, chi = iv[f"classical|{vr}"]
                    wr = (hi - lo) / (chi - clo)
                    cov = float(np.mean((lo <= r["theta_full"]) & (r["theta_full"] <= hi)))
                    new_acc.append(("4_permuted_not_narrower_than_classical", est, pop,
                                    f"permuted/{vr}", float(np.nanmedian(wr)), n_L))
                    new_acc.append(("4b_permuted_coverage_at_this_partition", est, pop,
                                    f"permuted/{vr}", cov, n_L))
    # match to committed rows: checks 4 and 4b repeat per n_L in file order
    old = acc_old.copy()
    old["n_L"] = old["detail"].str.extract(r"n_L=(\d+)").astype(float)
    worst, n_m, n_miss = 0.0, 0, 0
    detail_rows = []
    for t in new_acc:
        chk, est, pop, arm, val = t[:5]
        sel = (old.check == chk) & (old.estimand == est) & (old.population == pop) & (old.arm == arm)
        if len(t) == 6:
            sel &= old.n_L == t[5]
        m = old[sel]
        if len(m) != 1:
            n_miss += 1
            continue
        dv = abs(float(m.value.iloc[0]) - val)
        worst = max(worst, dv)
        n_m += 1
        detail_rows.append(dict(check=chk, estimand=est, population=pop, arm=arm,
                                n_L=t[5] if len(t) == 6 else np.nan,
                                value_committed=float(m.value.iloc[0]), value_module=val,
                                abs_diff=dv))
    rows.append(dict(part="1b_b1_acceptance", check="module in B1 configuration reproduces "
                     "b1_acceptance.csv values (CCRCC, checks 1-4b)",
                     statistic="max |new - committed|", value=worst, tol=tol,
                     passed=bool(worst <= tol and n_miss == 0 and n_m == len(old)),
                     detail=f"{n_m} of {len(old)} committed rows matched, {n_miss} unmatched"))
    return rows, pd.DataFrame(detail_rows)


def part2(tol=1e-12, seed="q1_acceptance_m1"):
    """m = 1: every clustered variance equals the spot i.i.d. one."""
    rng = E.seed_rng(seed)
    rows = []
    G, ncol = 30, 200
    for pop in ("spot",):
        y = rng.normal(size=(G, ncol))
        f = 0.6 * y + rng.normal(size=(G, ncol))
        D = dict(n=np.ones((G, ncol)), Sz=y, Sf=f, Szz=y * y, Sff=f * f, Szf=y * f)
        Lm = np.zeros((G, ncol), bool); Lm[:8] = True
        Um = ~Lm
        # The cross-fitted rule is left out here: it centres the labelled term within the two
        # halves, so at m = 1 its CR1 form equals the stratified i.i.d. form by construction,
        # and a check that cannot fail is not reported as one.
        for rule in ("none", "a_b1", "b_cluster"):
            lam = E.lambda_rule(rule, pop, D, Lm, Um, seed=seed)
            res = E.estimate(pop, D, Lm, Um, lam)
            v_iid = E.var_iid(res)
            for nm, fn in (("CR1", E.var_term_cr1), ("CR2", E.var_term_cr2)):
                v = fn(res["L"]) + fn(res["U"])
                dev = float(np.max(np.abs(v - v_iid) / v_iid))
                rows.append(dict(part="2_m_equals_1", check=f"{nm} equals spot iid at m = 1, "
                                 f"lambda rule {rule}", statistic="max relative |diff|",
                                 value=dev, tol=tol, passed=bool(dev <= tol),
                                 detail=f"G={G}, G_L=8, {ncol} replicates, population {pop}"))
    return rows


def main(argv=None):
    p = argparse.ArgumentParser()
    p.add_argument("--suff-dir", required=True)
    p.add_argument("--b1-dir", required=True)
    p.add_argument("--out-dir", required=True)
    p.add_argument("--n-boot", type=int, default=500)
    p.add_argument("--tol", type=float, default=1e-10)
    a = p.parse_args(argv)
    np.seterr(all="ignore")
    os.makedirs(a.out_dir, exist_ok=True)
    rows2 = part2()
    rows1, det = part1(a.suff_dir, a.b1_dir, a.n_boot, a.tol)
    df = pd.DataFrame(rows1 + rows2)
    df.to_csv(f"{a.out_dir}/q1_acceptance_part12.csv", index=False)
    det.to_csv(f"{a.out_dir}/q1_acceptance_b1_rows.csv", index=False)
    print(df.to_string(index=False))
    return 0 if bool(df.passed.all()) else 5


if __name__ == "__main__":
    sys.exit(main())
